services:
  backend:
    build: ./backend
    container_name: jwt_backend
    image: jwt_backend
    ports:
      - "${BACK_PORT}:3000"
    environment:
      - PORT=${BACK_PORT}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./data:/node_app/data
    networks:
      - jwt_app
  frontend:
    build: ./frontend
    container_name: jwt_frontend
    image: jwt_frontend
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - jwt_app
networks:
  jwt_app:
    driver: bridge
volumes:
  sqlite_data:
    name: jwt_sqlite
